plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
paginate: 10
paginate_path: "/page:num/"

# Site settings
title: maviteixeira.com | Programming and stuff
email: marcoo.teixeira@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog about programming and life. Posts will cover various topics.
url: https://maviteixeira.com # the base hostname & protocol for your site
twitter_username: maviteixeira
github_username:  maviteixeira

include: ['.well-known']

# Build settings
timezone: Campinas/Sao_Paulo
markdown: kramdown

lsi: false
safe: true
whitelist:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
